### ISSUE TITLE
Loss of input focus when entering a duty

### ISSUE THREAD

**Issue by Tashiro64** [Infiziert90/ChatTwo#118] opened 2024-09-01 14:58 UTC
according to https://github.com/Infiziert90/ChatTwo/issues/103 it has been fixed, but i'm still having the issue, plugin is up to date, tried disabling/reenabling. As it's been asked, i'm opening a new issue for this just so you can try to reproduce the problem and see for a potential fix. I wish i could help, but this stuff is out of my scope :/

https://github.com/user-attachments/assets/6982d45b-aaf2-48ee-a461-a40f92eca65e

**Comment by Kshumishyn** [comment] 2024-12-23 19:25
I can echo this sentiment/issue. I unfortunately like to confirm strats and the like upon entry or warn about food/repairs, and countless times have accidentally popped essential parts of openers because base-game chat lets me chat freely, but Chat2 rips focus randomly mid-sentence near the start of an instance.

**Comment by Infiziert90** [comment] 2024-12-23 19:32
Just to say that here, this can be a chat2 issue yes, but that can also be any of your other plugins stealing focus

Against the later I can do nothing, that would need to be fixed from the stealing plugins side

Easiest way to find out is /xldev and in one of the drop downs you can find a Window List, and there a By Focus Order, just check that chat2 stays the highest at all times

**Comment by Kshumishyn** [comment] 2024-12-23 19:35
> Just to say that here, this can be a chat2 issue yes, but that can also be any of your other plugins stealing focus
> 
> Against the later I can do nothing, that would need to be fixed from the stealing plugins side
> 
> Easiest way to find out is /xldev and in one of the drop downs you can find a Window List, and there a By Focus Order, just check that chat2 stays the highest at all times

Ah I didn't know I could test it like this, thank you, I'll try to replicate the issue and see whether it is reproduceable or even Chat2's fault at all.

**Comment by Kshumishyn** [comment] 2024-12-23 23:54
My apologies, you were absolutely correct that this was not a Chat2 problem, but rather Mare Synchronos who was snagging it on instance start with a PopupHandler. 
![image](https://github.com/user-attachments/assets/e2d5d39c-20f0-49b7-8224-794bc86cb298)

I contacted them and they were able to test something that could fix it and it worked, so here's hoping this won't crop up again. Sorry for bugging you with this and thank you for the advice!

**Comment by rootdarkarchon** [comment] 2024-12-23 23:59
Has been remedied in Mare 0.10.21

**Comment by Infiziert90** [comment] 2024-12-23 23:59
Closing this for now, if there is more such issues in the future, please check said ImGui Debugger for other plugins causing this

**Closed by Infiziert90** 2024-12-23 23:59 UTC
